server:
   port: 8080
student:
  name : zweo找个
  age : 8


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  show-sql: truess

logging:
  config: src/main/resources/log4j.properties
